In [1]:
import numpy as np

# Part A - Vectorized Programming with NumPy
## Task 1 - Arrays, Statistics, and Indexing

##### Generate Array A with 100 random integers. Set a random seed for reproducibility

In [3]:
np.random.seed(42)
A = np.random.randint(1, 101, 100)

print("Array A:")
print(A)

Array A:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49  91  59  42  92  60  80
  15  62  62  47  62  51  55  64   3  51   7  21  73  39  18   4  89  60
  14   9  90  53   2  84  92  60  71  44   8  47  35  78  81  36  50   4
   2   6  54   4  54  93  63  18  90  44  34  74  62 100  14  95  48  15
  72  78  87  62  40  85  80  82  53  24]


##### Use NumPy functions to find min, max, median, mean, and standard deviation of Array A.


In [4]:
print("Minimum:", np.min(A))
print("Maximum:", np.max(A))
print("Median:", np.median(A))
print("Mean:", np.mean(A))
print("Standard Deviation:", np.std(A))

Minimum: 2
Maximum: 100
Median: 54.0
Mean: 51.54
Standard Deviation: 29.278463074417004


##### Generate Array B with exactly 100 values using np.arange().

In [5]:
B = np.arange(1, 101)

print("\nArray B:")
print(B)
print("Number of values in B:", len(B))


Array B:
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Number of values in B: 100


##### Implement np.zeros() and np.ones(). Display shape and data type

In [6]:
zeros_array = np.zeros((3, 4))
ones_array = np.ones((3, 4))

print("\nZeros Array:")
print(zeros_array)
print("Shape:", zeros_array.shape)
print("Data Type:", zeros_array.dtype)

print("\nOnes Array:")
print(ones_array)
print("Shape:", ones_array.shape)
print("Data Type:", ones_array.dtype)


Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)
Data Type: float64

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape: (3, 4)
Data Type: float64


##### Implement np.linspace(). Briefly state how it differs from np.arange().

In [7]:

linear_array = np.linspace(0, 10, 6)

print("\nLinspace Array:")
print(linear_array)

print("\nDifference:")
print("np.arange() generates values using a step size.")
print("np.linspace() generates a specified number of equally spaced values.")


Linspace Array:
[ 0.  2.  4.  6.  8. 10.]

Difference:
np.arange() generates values using a step size.
np.linspace() generates a specified number of equally spaced values.


##### Create one 2D and one 3D array. Show shape, ndim, indexing, rows, columns, and slicing.


In [8]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n2D Array:")
print(array_2d)

print("Shape:", array_2d.shape)
print("Number of dimensions:", array_2d.ndim)

# Indexing
print("Element at row 0, column 1:", array_2d[0, 1])
print("Element at row 2, column 2:", array_2d[2, 2])

# Rows
print("First row:", array_2d[0])
print("Second row:", array_2d[1])

# Columns
print("First column:", array_2d[:, 0])
print("Second column:", array_2d[:, 1])

# Slicing
print("First two rows:")
print(array_2d[:2])

print("First two columns:")
print(array_2d[:, :2])


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Element at row 0, column 1: 2
Element at row 2, column 2: 9
First row: [1 2 3]
Second row: [4 5 6]
First column: [1 4 7]
Second column: [2 5 8]
First two rows:
[[1 2 3]
 [4 5 6]]
First two columns:
[[1 2]
 [4 5]
 [7 8]]


##### Use reshape() to create a matrix, then flatten it back to 1D.

In [9]:
array_3d = np.arange(1, 25).reshape(2, 3, 4)

print("\n3D Array:")
print(array_3d)

print("Shape:", array_3d.shape)
print("Number of dimensions:", array_3d.ndim)

# Indexing
print("Element [0, 1, 2]:", array_3d[0, 1, 2])
print("Element [1, 2, 3]:", array_3d[1, 2, 3])

# First 2D layer
print("First layer:")
print(array_3d[0])

# Second 2D layer
print("Second layer:")
print(array_3d[1])

# Slicing
print("First layer, first two rows:")
print(array_3d[0, :2, :])


3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Number of dimensions: 3
Element [0, 1, 2]: 7
Element [1, 2, 3]: 24
First layer:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second layer:
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
First layer, first two rows:
[[1 2 3 4]
 [5 6 7 8]]
